# Tutorial 1: Numerical Python (NumPy)

-----------------------------------------------------------

## Overview

## Learning Objectives

After this tutorial, you will have:
- made NumPy arrays
- Indexed arrays
- Used many useful NumPy functions

## Prerequisites
- basic python

## Getting Started

Numerical Python​, or "numpy" is one of the most popular modules used in Python.
     ​
The common standard in Python is to import numpy with the alias **np**.​

In [1]:
# Standard import of numpy
import numpy as np

# check the version
print(np.__version__)

1.26.4


## About Numpy

Numpy is considered a foundational module for Python high-end scientific computing.​

- It was originally designed to provide fast processing of multi-dimensional arrays and matrices.

- It is written partly in Python, but most of it is done in C or C++ to ensure highest possible performance.​

It has since evolved to provide robust mathematical operations, linear algebra and more.

Among the many components it provides is the **ndarray**.​

  - This is a high-performance array or vector and serves as one of the main classes for scientific computing.​

  - Has a **dtype** attribute and, unlike the tuple, only holds one type of element, much like a standard array.​

  - It is an N-dimensional array.​

    - Created with the **array()** function.

In [5]:
# Example using numpy for arrays
import numpy as np
 
# Create an array using a range.
arr1 = np.array(range(10))
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1)
# Create an array using a tuple.
arr_tup = np.array((1, 2, 3, 4, 5))
print(arr_tup)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5]


## Other ways to create arrays

There are some other functions to create convenient arrays

**arrange()**   

**ones()**      create an array of all ones

**zeros()**     create an array of all zeros

**identity()**  create an identity matrix

In [7]:
# More array creation
import numpy as np

np.ones((2,4))  # shortcut to create array and populate with 1's
np.zeros((2,4)) # shortcut to create array and populate with 0's
np.identity(5)  # shortcut to create identity array (1's on diagonal, 0's elswhere)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Attributes of numpy arrays

**ndim**: number of dimensions​

**shape**: list of the dimension lengths​

**size**: total number of elements​

**data**: elements of the array​

**dtype**: data type (beyond standard python date types)​

In [17]:
# Attributes
import numpy as np

arr1 = np.array(range(10))
arr2 = np.array([[1,2,3],[4,5,6]])

# Check the dimensions and types of the array.
# These are attributes, they don't need parantheses.
arr1.ndim)
arr2.ndim
arr2.shape
arr2.dtype

(2, 3)


dtype('int32')

## Data Types

Arrays are fast, partially due to the data type mapping to lower level calls. This is mostly transparent, but we can specify the **dtype**​

np.array(object\[,dtype\])​

See the full list of dtypes in your book on page 83, table 4-2​

We can change type using array.astype()​

In [7]:
# Dtype
ar3 = np.array([1,2,3,4,5,6],"float")
ar3.dtype

# change dtype
ar3 = ar3.astype("int")

NumPy provides a new set of data types to work with (in addition to what Python provides)​

> Unsigned integer
>
> Complex float
>
> Timedelta
>
> Datetime
>
> Object
>
> Unicode string
>
> Void (just a chunk of memory)

In [29]:
import numpy as np
# create array with defined data type
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


# Test Your Knowledge

Create an np array of the numbers 1-10

  - Change the dtype to a float

In [41]:
import numpy as np
j_arr=np.array(range(1,11,1), dtype='S')
print(j_arr)
print(j_arr.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9' b'10']
|S2


<div style="font-size:18px">Copy vs. View</div> 

Remember when we copied objects in Python?​

NumPy also provides methods for arrays​

**Copy** – Create a complete copy of an array (unlike the Python copy)​

**View** – Create a reference to the original array​

In [45]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
print(x)

[1 2 3 4 5]


NumPy allows us to check whether an array is the original array or one that has been “viewed”​

  - The original will have a base of None while the view points to the original​

In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


<div style="font-size:18px">Indexing</div>

For one dimensional arrays, we index in the usual way​

These slices are views, not copies…​

Changes are broadcasted if need be​

In [49]:
# Indexing (slicing)
line = np.arange(1,4*4*4+1)
line[0]
line[:4]
line[-1:-10:-1]  # the third number is the step
line[[1,2,1]]
line[:3] = 2
line

array([ 2,  2,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

# Test Your Knowledge

>  1. Create an np array of 10 elements (letters a-j)
>  2. Change the 4th element to the number 1 (does it work, what type is it?)

In [63]:
import numpy as np
let_arr=np.array(['a','b','c','d','e','f','g','h','i'])
print(let_arr)
let_arr[3]=1
print(let_arr)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i']
['a' 'b' 'c' '1' 'e' 'f' 'g' 'h' 'i']


## Reshaping

We can reshape an array with **array.reshape()**

In [65]:
# Reshaping array
line = np.arange(1,4*4*4+1)
rec= line.reshape(4,16)
rec.shape
square= line.reshape(8,8)
square.shape
cube = line.reshape(4,4,4)
cube.shape

(4, 4, 4)

<div style="font-size:18px">A Note</div> 

Avoid “rank 1” arrays as their behavior can be a little unpredictable​

Go with column vectors or row vectors instead​

Use assert to verify an object’s shape​

In [70]:
# say I need to create an array
#a = np.random.randn(5) # Rank 1 array – don’t use
#a.shape() # = (5,) shape of array

# better
a = np.random.randn(5, 1) # column vector
a = np.random.randn(1, 5) # row vector
assert(a.shape == (5, 1)) # verify shape is correct

AssertionError: 

<div style="font-size:18px">Multi Dimensional Index</div>

Indexing gets more interesting with multiple dimensions​

Start with first axis, separate by commas

In [14]:
# Indexing Multiple Dimensions
square[0]
square[0,:] # equivalent, implied
rec[3,15]
rec[3][15] # equivalent

cube[0]
cube[0,2,1]
cube[:,0,0]

array([ 1, 17, 33, 49])

<div style="font-size:18px">Flattening an Array</div> 

Any multidimensional array can be “flattened” or turned into a single dimensional array using reshape​

In [15]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# Test Your Knowledge

> 1. Create a 2x5 array of the numbers 1-10
> 2. Transpose the array, change rows to columns, columns to rows
> 3. Reshape the array, make it a 2x2x3 array
> 4. Add the numbers 11 and 12 to the missing cells

## Boolean indexing

We can also index using boolean values​

To show this, we introduce a normal random number generator from **numpy.random**….more on this later. ​

These boolean values can be along an axis, or cover all elements

In [16]:
# Boolean Index
np.random.seed(123)
norm_ar = np.random.randn(10).reshape(5,2)
tf = norm_ar > 1

norm_ar[tf]

array([1.65143654, 1.26593626])

# Test Your Knowledge

> 1. Create a 2x5 array of the numbers 1-10
> 2. Create a Boolean index on the array
> 3. Use it to retrieve elements greater than 5
> 4. Calculate the mean of the array

## Iterating a NumPy array

Iterate a NumPy array just like a Python tuple or list​

NumPy will iterate row by row or column-wise if you specify​

In [2]:
import numpy as np
# 1-dimensional array
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [3]:
# 2-dimensional array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

# also 2-d array
for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


Iterating through a multi-dimensional array requires a lot of for loops which can be awkward to NumPy provides the **nditer()** method to “flatten” out the array for iteration​

In [17]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)

for x in np.nditer(arr):
  print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8


## NumPy Functions

NumPy provides many functions you would expect in highly statistical applications such as data science

In [21]:
# NumPy Functions
np.mean(norm_ar)

0.5855124016656363

In [22]:
np.mean(norm_ar,0)

array([-0.81818202, -0.56038955])

In [23]:
np.mean(norm_ar,1)

array([-0.5428153 , -0.75314736, -0.28930013, -1.42779594, -0.4333702 ])

In [24]:
np.var(norm_ar)

0.5855124016656363

In [25]:
# creating a uniform [0,1] distribution
np.random.rand(4,4)

array([[0.43857224, 0.0596779 , 0.39804426, 0.73799541],
       [0.18249173, 0.17545176, 0.53155137, 0.53182759],
       [0.63440096, 0.84943179, 0.72445532, 0.61102351],
       [0.72244338, 0.32295891, 0.36178866, 0.22826323]])

In [26]:
# creating a randomized normal distribution with defined characteristics (mean=0,var=1)
np.random.randn(2,2,2)
4*np.random.randn(2,2,2) + 10

array([[[13.70984973,  9.30545727],
        [10.01138366, 12.75289084]],

       [[ 6.48185463, 11.1345093 ],
        [ 6.77853393,  3.08932202]]])

In [27]:
# creating an array with a randomized binomial distribution with defined characteristics
np.random.binomial(n=100,p=0.2,size=50)

array([24, 17, 20, 29, 20, 21, 15, 24, 21, 20, 18, 18, 19, 22, 25, 20, 22,
       21, 21, 22, 24, 15, 23, 17, 17, 21, 15, 25, 21, 22, 12, 21, 20, 16,
       16, 22, 18, 22, 20, 19, 26, 24, 18, 13, 18, 19, 22, 31, 18, 23])

<div style="font-size:18px">More on Arrays</div> 

Arrays can also be split, i.e. taking a single array and breaking it up into multiple sub-arrays​

The following code takes one array and splits it into 3 (equal parts)​

In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


NumPy allows you to conduct array searches using a **where()** method​

The return value is an array of indexes where the search condition was satisfied​

In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


Finally you can sort arrays using the sort() method​

  - The return value is a copy of the array sorted​

Note the sort is only ascending. To do a descending sort you need to reverse the array using slicing​

In [34]:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
print(np.sort(arr)[::-1])  # sort descending

[0 1 2 3]
[3 2 1 0]


# Test Your Knowledge

> 1. Create a 3x3 array of random numbers between 1 and 20
> 2. Convert the array to a nested list
> 3. Flatten and sort the original array

Do the NumPy Lab from the document: NumPyLab.docx


# Summary

In this tutorial, you have learned the many functions associated with the NumPy array. 

The next module introduces you to [Pandas](./Submodule_2_Tutorial2_Pandas.ipynb)

## Clean up
Remember to shut down your Jupyter Notebook instance when you are done for the day to avoid unnecessary charges. You can do this by stopping the notebook instance from the Cloud console.